baseURL = "https://equaldev.netlify.app/"
languageCode = "es-us"
title = "Diseño de páginas web | EqualDev "
theme = "equalDevSite"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
[[Params.listeLangues]]
code = "fr"
[[Params.listeLangues]]
code = "en"

# meta data
author = "EqualDev - diseño y desarrollo de páginas web"
description = "Diseño y desarrollo de páginas web"

# Gestion des langues : FR / EN / NL / DE
[Languages]
############ 1 - Sitio en Inglés
[Languages.fr]
weight = 1
languageCode = "fr-fr"
title = "Web Develop | EqualDev "
dateFormat = "2 January 2006"

home = "FR Home"
logo = "images/logo.svg"
menufixed = false

footerDescription = "Group of Professionals mainly oriented to web design and with extensive experience in what we do."
footerServiceTitle = "Services"
footerQuicklinkTitle = "Quick Access"
footerAboutTitle = "EqualDev"
footerSubscribeTitle = "Subscribe"

# Hero Area Section
[Languages.fr.params.hero]
enable  = true
heading = "Professional Web Design and Business Web Development"
description = "We are a design and digital marketing agency based in Buenos Aires ... We develop and implement solutions with real results on digital platforms that allow companies to exploit their full potential on the web"
button  = true
btnText = "I want to design my website"
btnURL  = "/fr/contact"
videoThumb = "images/slider/video-player-thumb3.jpg"
videoURL   = "https://player.vimeo.com/video/527355855"

# About 2 Section
[Languages.fr.params.aboutSm]
enable  = true
title   = "We have been passionately exploring the digital landscape for a long time."
description = " We are a group of professionals mainly oriented to web design and with extensive experience in what we do. With us you can develop your institutional website, create your online store and sell your products, publish your digital newspaper, create your blog, develop a catalog offering your products or services, we also generate landing pages focused mainly on search engine visibility to work directly on them. with advertising in Google Adwords."

# Blog Section On Homepage
[Languages.fr.params.blog]
enable  = true
topTitle= "News from the digital worldl"
title   = "Blog"
subtitle= "We publish in this blog about web design, positioning, advertising, content marketing and more."

# Contact Section
[Languages.fr.params.contact]
enable  = true
topTitle= "Contact"
title   = "Hire our services"
subtitle= "Complete the form with your data and leave us your query. An advisor will contact you shortly to design your website. Specify all the requirements of your website and if you have reference websites, detail them in your message."
address = "Av. Rivadavia 8000 <br> Floresta , Argentina"
phone   = "(11) 4982 9215"
fax     = "+54 9 11 3112 7022"
facebook= "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin= "https://www.linkedin.com/"
dribbble= "https://dribbble.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "-34.63262983538989"
mapLongitude= "-58.476557175585064"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.fr.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Together we can create something amazing"
subtitle= "We are an experienced company with specialized professionals, <br> in the design of web solutions"
btnText = "Contact me"

############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "EqualDev - Diseño de páginas web"
dateFormat = "January 2, 2006"
home = "Inicio"
logo = "images/logo.svg"
menufixed = false

footerDescription = "Grupo de Profesionales orientados principalmente al diseño web y con amplia experiencia en lo que hacemos."
footerServiceTitle = "Servicios"
footerQuicklinkTitle = "Accesos Rápidos"
footerAboutTitle = "EqualDev"
footerSubscribeTitle = "Subscrirse"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Diseño Web Profesional y Desarrollo Web Empresarial"
description = "Somos una agencia de diseño y marketing digital con sede en Buenos Aires...Desarrollamos e implementamos soluciones con resultados reales sobre plataformas digitales permitiendo a las empresas explotar todo su potencial en la web"
button  = true
btnText = "Quiero diseñar mi página web"
btnURL  = "/en/contact"
videoThumb = "images/slider/video-player-thumb3.jpg"
videoURL   = "https://player.vimeo.com/video/527355855"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Nos dedicamos a explorar el panorama digital con pasión desde hace mucho tiempo."
description = " Somos un grupo de profesionales orientados principalmente al diseño web y con una amplia experiencia en lo que hacemos. Con nosotros podrás desarrollar tu página web institucional, crear tu tienda online y vender tus productos, publicar tu diario digital, crear tu blog, desarrollar un catálogo ofreciendo tus productos o servicios, también generamos landing pages enfocadas principalmente a la visibilidad en buscadores para trabajarlas directamente con publicidad en Google Adwords.?"

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
topTitle= "Novedades del mundo digital"
title   = "Blog"
subtitle= "publicamos en este blog sobre diseño web, posicionamiento, publicidad, márketing de contenidos y más."

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "Contacto"
title   = "Contrata nuestros servicios"
subtitle= "Complete el formulario con sus datos y dejenos su consulta. Un asesor se comunicará con usted a la brevedad para hacer el diseño de su página web. Especifíque todos los requisitos de su sitio web y si tiene paginas web de referencia detalle las mismas en su mensaje."
address = "Av. Rivadavia 8000 <br> Floresta , Argentina"
phone   = "(11) 4982 9215"
fax     = "+54 9 11 3112 7022"
facebook= "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin= "https://www.linkedin.com/"
dribbble= "https://dribbble.com/"
instagram= "https://www.instagram.com/"
mapLatitude = "-34.63262983538989"
mapLongitude= "-58.476557175585064"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Juntos podemos crear algo increíble"
subtitle= "Somos una empresa experimentada con profesionales especializados , <br> en el diseño de soluciones web"
btnText = "Contactate"



# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "nosotros"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "servicios"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "portfolio"
url     = "portfolio"
weight  = 4
[[menu.nav]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.nav]]
name    = "contacto"
url     = "contact"
weight  = 6

# Footer Service Menu
[[menu.service]]
name    = "graphicdesign"
url     = "service"
weight  = 1
[[menu.service]]
name    = "webdesign"
url     = "service"
weight  = 2
[[menu.service]]
name    = "webdevelopment"
url     = "service"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "partners"
url     = "service"
weight  = 1
[[menu.quicklink]]
name    = "about"
url     = "blog"
weight  = 2
[[menu.quicklink]]
name    = "faqs"
url     = "about"
weight  = 3
[[menu.quicklink]]
name    = "badges"
url     = "contact"
weight  = 4
